### ISSUE TITLE
Providing support for legacy browser (IE7-8) in client

### ISSUE THREAD

**Issue by voltagex** [Glimpse/Glimpse#399]
![pubsub](https://f.cloud.github.com/assets/159567/685561/6403f50c-da37-11e2-9603-5dfab308c0dc.png)

The issue is IE8 doesn't seem to support indexOf and JSON.

**Comment by issafram** [comment]
Awesome that this problem is fixed.  Only over a year old guys.

**Comment by avanderhoorn** [comment]
@issafram When you run and contribute to a project as large as Glimpse you will understand that we just have to prioritise. Supporting older browsers isn't a technical one but more of a question of maintaining support and finding the man hours to do it. Given the hundreds of different configurations, setups, environments, etc that we already support, maintaining support for browsers that are going on 10 years old isn't on the core priority list. 

I'm assuming you have read through this issue and can see that we were quite happy to help support the effort if someone stepped forward to help contribute the required changes. Since the original discussions, no one has seen it enough of a priority to put their money were their mouth is. I suspect that this is because most people have access to newer browsers which they can run Glimpse from when required. And the fact that Glimpse supports remote session monitoring which allows you to follow requests happening for any browser. 

If you are interested in helping out with this effort, as I've said to others, we would love the Pull Request. I would simply encourage you to ready carefully through the above to see the ground already covered and the desired approach from others that have put thought behind it.

**Comment by issafram** [comment]
@avanderhoorn I understand.  Corporate environment though.  Trying to support it.  For now using a `IRuntimePolicy` to disable Glimpse for older browsers.

**Comment by avanderhoorn** [comment]
Makes sense. Also note that you could create your own polyfill and include it when needed.

**Comment by voltagex** [comment]
I apologise for abandoning this. My own situation is as follows: management
were convinced to upgrade to IE11 which removed my need for this fix.

**Comment by nikmd23** [comment]
Haha @voltagex I'd call that the "Management Push Request" :wink:

**Comment by avanderhoorn** [comment]
@voltagex Personally the fact that you didn't do this is a good thing :D
