### ISSUE TITLE
Ajax requests to ASP.NET WebForms WebMethods are not captured

### ISSUE THREAD

**Issue by shrichards** [Glimpse/Glimpse#596]
I have a simple ASP.NET WebForm page with a single server-side `WebMethod`, and the following Glimpse packages installed:

* Glimpse.Core v1.7.0
* Glimse.AspNet v1.5.0
* Glimpse.WebForms v1.0.1

The entirety of the code-behind is:

```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Services;

namespace WebFormAjaxTest
{
    public partial class _Default : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {
        }
        [WebMethod]
        public static string GetTheTime()
        {
            return DateTime.Now.ToShortTimeString();
        }
    }
}
```

The client side code consists of a single button that, when clicked, makes an ajax request to the `GetTheTime` method in the code-behind:

```html
<%@ Page Title="Home Page" Language="C#"  AutoEventWireup="true"  CodeBehind="Default.aspx.cs" Inherits="WebFormAjaxTest._Default" %>
<html>
    <head>
        <title>WebForm Ajax Test</title>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    </head>
    <body>
        <div id="the-time">
        </div>
        <input type="button" id="get-time" value="Get The Time" />

        <script type="text/javascript">

            $(function () {
                $("#get-time").click(getServerTime);
            });

            function getServerTime() {
                $.ajax({
                    type: "POST",
                    url: "Default.aspx/GetTheTime",
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    success: function (msg) {
                        $('#the-time').text(msg.d);
                    }
                });
            }
        </script>
    </body>
</html>
```

*These ajax request appear in neither the HUD, nor in the Glimpse Ajax tab.*

(Here's a solution with this code in it: https://dl.dropboxusercontent.com/u/2434695/WebFormAjaxTest.zip)

It's not immediately clear to me whether or not Glimpse supports capturing this type of request, though it would be immensely useful for me.

If this is currently not supported, I'd be more than willing to take a crack at implementing it (with a bit of direction).

**Comment by hbopuri** [comment]
Does glimpse work for Ajax calls using EXTJS (3.4) framework. I have ASP.NET 4.0 Web Form application but it is a SPA (single page application), I have only one index.aspx everything else on the application is using ExtJS library Ajax calls. My ajax calls are on a click events. I don't see any logs in Ajax tab on glimpse console. Am I missing any configuration or glimpse has not yet come to that point to support such requests?

I am assuming ExtJS should not be a factor for glimpse not capturing Ajax calls, could it be SPA? but I  cant be certainly sure. Can some one help me resolve this...

**Comment by CGijbels** [comment]
@hbopuri do the requests show up in the history tab?

Are there differences in the way the Ajax calls are being made (those that end up being marked as Ajax methods and those that aren't) ?

Can you check with developer tools (F12) in the browser if the requests that are not being detected as Ajax requests (but should), if they contain the __X-Requested-With__ header with the value __XMLHttpRequest__ ?

**Comment by hbopuri** [comment]
@CGijbels on developer tools, Network tab it is capturing all requests like www.{myDomain}/controllers/{SomeClass}.ashx as X-Requested-With:XMLHttpRequest

But on glimpse "ajax" or "history" tabs, it only captures www.domain/controllers/ErrorController.ashx requests. All requests are sent as X-Requested-With:XMLHttpRequest

I have attached screen shots, hope those will give you more details, also if you notice, glimpse did not capture anything for SQL as well.

![cap1](https://cloud.githubusercontent.com/assets/3410059/5667407/80f59a78-9735-11e4-92dc-271da49ee605.PNG)
![cap2](https://cloud.githubusercontent.com/assets/3410059/5667406/80f0e23a-9735-11e4-9ade-39f34f47bdb5.PNG)

**Comment by CGijbels** [comment]
@hbopuri did you enabled Glimpse logging ([see here on how to do that](http://getglimpse.com/Docs/Configuration#configuring-logging)) ? Do you see anything special in those logs like requests being ignored etc...?

**Comment by hbopuri** [comment]
@CGijbels please use the link to access the log https://www.dropbox.com/s/tcsdnvm0k4pz9pu/Glimpse.log?dl=0
I don't see any ignore logs.

FYI: I have my glimpse configuration as below

<glimpse defaultRuntimePolicy="On" endpointBaseUri="~/Glimpse.axd">
      
	<logging level="Trace" />
  <inspectors>
    <ignoredTypes>
    </ignoredTypes>
  </inspectors>
  <runtimePolicies>
    <ignoredTypes>
      <add type="Glimpse.AspNet.Policy.LocalPolicy, Glimpse.AspNet" />
    </ignoredTypes>
  </runtimePolicies>
  
    </glimpse>

**Comment by CGijbels** [comment]
@hbopuri from what I can see from the logs is that you seem to have 2 different problems:

- first you don't seem to be using the correct Glimpse.EF version package for the EF version you are using, as the log contains errors loading the correct version of EF (maybe you are missing a binding redirect?) Either way, that is the reason why you don't have any SQL logs in Glimpse

- secondly, I see a lot of Glimpse log entries indicating that Glimpse is disabled for the given request due to a mismatch with the StatusCode being returned, which is the reason why there isn't any logging.
  > 2015-01-08 13:40:14.0343 | DEBUG | RuntimePolicy set to 'Off' by IRuntimePolicy of type 'Glimpse.Core.Policy.StatusCodePolicy' during RuntimeEvent 'EndRequest'. | 
2015-01-08 13:40:14.0413 | DEBUG | RuntimePolicy set to 'Off' by IRuntimePolicy of type 'Glimpse.Core.Policy.StatusCodePolicy' during RuntimeEvent 'EndRequest'. | 
2015-01-08 13:40:14.0573 | DEBUG | RuntimePolicy set to 'Off' by IRuntimePolicy of type 'Glimpse.Core.Policy.StatusCodePolicy' during RuntimeEvent 'EndRequest'. | 
2015-01-08 13:40:14.0573 | DEBUG | RuntimePolicy set to 'Off' by IRuntimePolicy of type 'Glimpse.Core.Policy.StatusCodePolicy' during RuntimeEvent 'EndRequest'. | 
2015-01-08 13:40:14.0773 | DEBUG | RuntimePolicy set to 'Off' by IRuntimePolicy of type 'Glimpse.Core.Policy.StatusCodePolicy' during RuntimeEvent 'EndRequest'. | 
2015-01-08 13:40:14.0773 | DEBUG | RuntimePolicy set to 'Off' by IRuntimePolicy of type 'Glimpse.Core.Policy.StatusCodePolicy' during RuntimeEvent 'EndRequest'. | 

I do see in the printscreens that calls to ErrorController are being logged and are marked as an Ajax call, so no issue over there.

I think we need to look at the server code responding to those Ajax calls, they are by any means not `[WebMethod]` decorated methods? Because if that is the case, well that is still an issue as this issue is exactly describing that problem and is still not closed (although a solution was in the works, but got put on a side track as it will be solved in v2)

**Comment by hbopuri** [comment]
@CGijbels I am not using EF in my application, I am using ADO.NET, since my SQL tab was disabled, I just tried installing Glimpse.EF to see if it has any dependency on that. Now I uninstalled Glimpse.EF

Problem 2) Yes these are all not marked as [WebMethod], but little confused, how would the ErrorController requests are logged, that is also not marked as [WebMethod]

**Comment by avanderhoorn** [comment]
@hbopuri How did you end up going with this? Did you make any more progress on your problem, or are we still exactly where you were before?

**Comment by hbopuri** [comment]
@avanderhoorn no progress yet, according to @CGijbels  it will be solved in v2

**Comment by vm1991** [comment]
I have an  ASP.NET 4.5 MVC application.It is a Single Page Application and Ajax calls are made on all click events .Glimpse Tab content gets refreshed only when PostBack happens.Is there any way that I can force the Glimpse Tabs data to get refreshed for each Ajax calls or on any click event rather than going and inspecting each ajax call individually in Ajax tab.

**Comment by avanderhoorn** [comment]
@vm1991 You could conceivably do this via JavaScript. You would have to take a look at the code that gets executed when a new request is manually selected from the Ajax call and just automate it. I don't think it wouldn't be something that we build in out of the box, but you should be able to get it up and running yourself. Once you have had a look and traced the code, let me know if you need any pointers.
