### ISSUE TITLE
Memory increase using asp.net webforms

### ISSUE THREAD

**Issue by lemkepf** [Glimpse/Glimpse#681]
We deployed glimpse last week to production and have had nothing but memory issues ever since. Normally run about 2gb in memory, with glimpse it would creap up to our max of 6gb very quickly. We had to turn glimpse off in prod. 

If we had: 

```xml
<glimpse defaultRuntimePolicy="On" endpointBaseUri="~/Glimpse.axd">
```

but only allowed admins to have it actually on we ramped up memory within 20 min. 

If we had: 

```xml
<glimpse defaultRuntimePolicy="Off" endpointBaseUri="~/Glimpse.axd">
```
we ramped up memory within an hour. 

With glimpse out of the web.config all together we are sitting at our normal 2gb usage pretty steady all day. 

The memory dumps I'm seeing haven't really given me much info on something blatant. One thing I did notice in the performance counters is the Large Object Heap is much much smaller than what it was before took glimpse out. Not sure if that has anything to do with it.

**Comment by LodewijkSioen** [comment]
We're on 1.8.1 and we might be having this problem. I will be removing Glimpse from the Web.config tonight and I'll report back if this reduced the memory footprint

**Comment by Fienix** [comment]
I have version 1.8.6 and experience this memory leak as well. I usually sit around 350-550MB for my application, but with glimpse turned on, I reach 2GB in < 10 requests. If I go to /glimpse.axd and "Turn Glimpse Off", the issue subsides. I have a attached my tabs that I have enabled.

I'd be willing to help out with testing this problem so it can get resolved, as I see comments surrounding this issue since 2013. Would like to see this get fixed so Glimpse is usable again.

![glimpsetabs](https://cloud.githubusercontent.com/assets/206516/11860477/e421ebe8-a43a-11e5-910f-773f022fab0a.png)

**Comment by cperriot** [comment]
I have version v1.8.6 and experiencing the same issue.
We have a big,old  webforms application and glimpse is not usable.
When memory profiling the application I saw strange things that I have not been able to understand.
The test have been done on a developper machine with only one user connected. The memory usage was steady until I set the cookies to on  and hit refresh on the page (red marker). The page refresh was very slow and the memory is consumed and freed in a strange pattern indefinitely from that moment even without activity on the website.

![image](https://cloud.githubusercontent.com/assets/6649470/13822320/7652ce5e-eba5-11e5-83b0-1b5afe688526.png)

**Comment by cperriot** [comment]
After additional tests, I found that the request : /Glimpse.axd?n=glimpse_request&requestId=ace0fbc3-1be7-4a66-b041-864ec6a20586&hash=5d23d7f3&callback=glimpse.data.initData HTTP/1.1
is usually getting a few hundreds kilobytes but a few hundreds megabytes when cache tab is active.
