### ISSUE TITLE
Any plans to support AngularJS?

### ISSUE THREAD

**Issue by shansubra** [Glimpse/Glimpse#697]

**Comment by Korayem** [comment]
When using AngularJS and Web API, sometimes AJAX calls don’t show up in Glimpse. It turns out there are a couple of configurations in AngularJS $http and Glimpse that need to be made.

By default, Glimpse only detects requests that return HTTP 200 (and maybe a couple of others). REST APIs (like ones created with ASP.NET Web API) often return 201, 202, and 204. These have to be added to the Glimpse configuration section in web.config

Glimpse identifies AJAX calls by the X-Requested-With: XMLHttpRequest header. AngularJS $http calls do not include this header by default, so they do not show up in the AJAX panel in Glimpse.

Source: http://anthonychu.ca/post/getting-angularjs-http-and-web-api-to-work-with-glimpse/

**Comment by avanderhoorn** [comment]
As a side note, when Glimspe v2 is released for .net 4.5.x this shouldn't be a problem any more. Out of the box, these cases will be supported by default.
