### ISSUE TITLE
Problem with latest version and cache tab

### ISSUE THREAD

**Issue by d3bgger** [Glimpse/Glimpse#735]
Hello

i just updated my glimpse to latest version but when it is shown on page, it displays:

No data has been found. This could be caused because:
- the data is still loading by the client, or
- no data has been received from the server (check to see if the data & metadata payloads are present), or
- no plugin has been loaded, or
- an error has been thrown in the client (please check your JavaScript console and let us know if anything is up).

in the meanwhile the ram usage of the web app is constantly increasing...

i've created a log file and it seems tha glimpse keeps restarting untill i end the app pool process. (is there a way i can attach the log file?)

if i disable the cache tab, then everything works normally!

thanks in advance

**Comment by rk1984** [comment]
I see it's closed, but if anyone have same problem, might be the same as my case.
I'm getting same issue and it's because I've already has installed hangfire.io package.
Once I've commented storage config, everything worked fine.
You will see these line of code required to config hangfire storage, just comment them and Glimpse should be happy

<pre>
            app.UseHangfire(config =>
            {
                config.UseSqlServerStorage("AppContext");
                config.UseServer();
            });
</pre>

I'll post here if I'll be able to make them both working fine.
