### ISSUE TITLE
Glimpse ASP.NET MVC 4 with MVC Sitemap Provider

### ISSUE THREAD

**Issue by joetherod** [Glimpse/Glimpse#877]
I have 2 applications using glimpse, ASP.NET MVC 4 and EF 6. All works as expected for the application except for the one that is using the MvcSiteMapProvider.MVC4. When I make a request to get the sitemap.xml it errors out whether I have glimpse enabled or not.

The error I am getting is below. Seems to be related to the sitemap provider. Glimpse may be conflicting with how this is works. Please advise.

```
Resolution of the dependency failed, type = "MvcSiteMapProvider.Web.Mvc.XmlSiteMapController", name = "(none)".
Exception occurred while: while resolving.
Exception is: InvalidOperationException - The type IXmlSiteMapResultFactory does not have an accessible constructor.
-----------------------------------------------
At the time of the exception, the container was:

  Resolving MvcSiteMapProvider.Web.Mvc.XmlSiteMapController,(none)
  Resolving parameter "xmlSiteMapResultFactory" of constructor MvcSiteMapProvider.Web.Mvc.XmlSiteMapController(MvcSiteMapProvider.Web.Mvc.IXmlSiteMapResultFactory xmlSiteMapResultFactory)
    Resolving MvcSiteMapProvider.Web.Mvc.IXmlSiteMapResultFactory,(none)
```

**Comment by CGijbels** [comment]
@joetherod I'm not seeing any Glimpse specific code in the stack trace? Have you tested it without Glimpse being installed?

**Comment by joetherod** [comment]
Yes. The sitemap.xml returns fine if I remove all of the config entries for glimpse. I turned on logging for glimpse and didn't see anything. There must be a handler conflict between the two.

**Comment by CGijbels** [comment]
@joetherod can you provide us with the steps to reproduce this based on a new MVC4 project?, something like 

- Create new MVC4 project
- Install-Package MvcSiteMapProvider.MVC4
- Build
- Access http://site/sitemap.xml => Success
- Install Glimpse
- Rebuild
- Access http://site/sitemap.xml => Fail?

Because that is what I did and I did not end up with a Fail at the end but with a success.

Do you use another DI container than the one coming out of the box for the mvc sitemap provider?

**Comment by joetherod** [comment]
Attached is my web.config with all the glimpse settings commented out. (some settings removed for privacy) MVC Sitemap provider settings are there, nothing done differently for that.

Nuget packages.config. Shows all other referenced packages.

MVC Sitemap. I make use of their dynamic site provider to create the sitemap.xml file from data in my database. (Some info removed for privacy)

**Comment by CGijbels** [comment]
@joetherod could you add those settings directly on the GitHub site? because the attached files did not make it to the site :-(

just to recapitulate, but you are getting the exception when requesting the http://site/sitemap.xml ?
If there is an issue then it might be related to the custom sitemap provider you are using. I guess you've done something like described [here](https://github.com/maartenba/MvcSiteMapProvider/wiki/Sitemaps-XML-Protocol-Endpoint-for-Search-Engines) but then they mention that you need an external DI container...

Is the stacktrace you mentioned above, the complete stacktrace?

**Comment by joetherod** [comment]
![packages](https://cloud.githubusercontent.com/assets/2990362/6061148/2c770bb4-ad13-11e4-9d27-87a510023f70.png)
![web](https://cloud.githubusercontent.com/assets/2990362/6061150/34ffc8ca-ad13-11e4-90ee-199ce5d0e095.png)
![mvc](https://cloud.githubusercontent.com/assets/2990362/6061151/38dff8fc-ad13-11e4-8387-a4bbff4f81a5.png)

I had to rename the files to upload. Rename them back, web.config, packages.config, mvc.xml

The sitemap.xml worked before I added glimpse and works when I remove all glimpse settings in the config. I am using Unity for a DI.

Exception:

Resolution of the dependency failed, type = "MvcSiteMapProvider.Web.Mvc.XmlSiteMapController", name = "(none)".
Exception occurred while: while resolving.
Exception is: InvalidOperationException - The type IXmlSiteMapResultFactory does not have an accessible constructor.
-----------------------------------------------
At the time of the exception, the container was:

  Resolving MvcSiteMapProvider.Web.Mvc.XmlSiteMapController,(none)
  Resolving parameter "xmlSiteMapResultFactory" of constructor MvcSiteMapProvider.Web.Mvc.XmlSiteMapController(MvcSiteMapProvider.Web.Mvc.IXmlSiteMapResultFactory xmlSiteMapResultFactory)
    Resolving MvcSiteMapProvider.Web.Mvc.IXmlSiteMapResultFactory,(none)

**Comment by avanderhoorn** [comment]
@joetherod Are you able to put the name of the new files up, I can't seem to be able to download/view the files.

**Comment by joetherod** [comment]
I couldn't upload files unless they were image files. I renamed them to upload them. You need to rename them back. Web.config, packages.config, and site.xml.

**Comment by avanderhoorn** [comment]
But when I go to the link I get a 404.

**Comment by joetherod** [comment]
Is there another way I can send you the files? This email address?
