### ISSUE TITLE
Install Glimpse now I cannot add service references?

### ISSUE THREAD

**Issue by KevinBurton** [Glimpse/Glimpse#892]
![glimpse](https://cloud.githubusercontent.com/assets/2643566/6846399/1b763d40-d38c-11e4-9802-e69e45d0bd0e.jpg)
I installed glimpse and now I get a warning and an error when adding a service reference that Glimpse 1.8.2 could not be found or loaded. I looked in my packages folder and I have Glimpse 1.8.6 installed. Apparently there is still some reference to 1.8.2 having to do with adding a service reference in Visual Studio but I have not been able to find it. Ideas?

**Comment by CGijbels** [comment]
@KevinBurton Can you give me the list of Glimpse related NuGet Packages installed in the project where you are adding your service reference?

Just check the packages.config file

My first idea is that the custom tool generating the client classes when adding the service reference, is not talking the web.config into account, where the binding redirects are being configured. Most likely it is loading all assemblies in the project's bin folder into memory and applying some reflection upon it, hence a specific Glimpse assembly, one depending on Glimpse.Core 1.8.2, is loaded, but since the bin folder most likely contains a newer version of the Glimpse.Core and there are no binding redirects defined for that custom tool process the tool crashes

I'm not sure if that can be solved directly, and somehow I guess other assemblies added by means of NuGet packages might have the same problem, but to be sure we first need the information above to try to reproduce it, just to make that is actually the problem

**Comment by KevinBurton** [comment]
I have attached the packages.config which should give you an idea of the packages that I have installed. Ntoice that the config file seems to have it right. it is referenceing 1.8.6
![glimpse](https://cloud.githubusercontent.com/assets/2643566/6847639/0ff09164-d396-11e4-9d82-73d86f544379.jpg)

**Comment by KevinBurton** [comment]
By the way I have tried rebooting to eliminate the possibility of something loaded in memory. I didn't notice any Glimpse related assemblies in the GAC. But as you said it may be another assembly that references an older version of Glimpse.

**Comment by avanderhoorn** [comment]
Are you able to create a sample which reproduces the issue?

**Comment by KevinBurton** [comment]
It seems that when I install Glimpse.MVC4 it is when I start seeing the problem. I can install Glimpse Core and Glimpse ASP.NET and the project doesn't have a problem but as soon as I install Glimpse MVC4 I start seeing the error. 
I have a project in my Dropbox account - https://www.dropbox.com/s/hb3prz7p7p0u3zp/OaisysDemo.zip?dl=0
The state of the project is Glimpse MVC4 has not be installed yet. This project has two web references. If these require access that you don't have remove them and try to add another reference that you know will work. I suspect that after Glimpse MVC4 has been install the import of the service reference (VS 2013) will fail.

**Comment by avanderhoorn** [comment]
For this sample, is it possible that you start with a new project and add
in components until you find the combination that breaks, or from the
project you have remove everything that doesn't have to do with the problem
until you find the issue?

**Comment by KevinBurton** [comment]
The combination that breaks is I add Glimpse Core and Glimpse ASP.NET and the step that breaks is installing Glimpse MVC4.

**Comment by CGijbels** [comment]
@KevinBurton before you install Glimpse.Mvc4 do you see a Glimpse 1.8.2 being mentioned in the dependency graph?

Can you check with the Glimpse.Elmah assembly as well? (I saw that package in your first list of packages)

Either way, I can build your solution you made available on Dropbox, and I was able to add a reference to another service and compile without any problem. 

- So I downloaded the zip
- opened solution in VS2013
- compiled => no issue
- added another service => no issue
- compiled again => no issue
- removed added service
- installed package Glimpse.Mvc4 => no issue
- compiled => no issue
- added another service => no issue
- compiled => no issue
- added even Glimpse.Elmah => no issue
- compiled => no issue

so I have no idea where to go further

can you enable logging of assembly bindings? so that you can see the load failure with the [fuslogvw.exe](https://msdn.microsoft.com/en-us/library/e74a18c4%28v=vs.110%29.aspx) that might give you an idea about the application directory from where the custom tool is started and where it starts looking for the Glimpse assembly...

**Comment by KevinBurton** [comment]
It is definitely Glimpse MVC4. When I add it an try to update the service reference I get the error and warnings. Once it is removed I no longer get the error. I am not entirely familiar with fuslogvw. But, invoking it in an administrator window yields no information. It is blank both before and after.

**Comment by CGijbels** [comment]
@KevinBurton it is quite possible that the Glimpse.Mvc4 might trigger the issue, but the question remains whether it is the root cause, which for me is still not clear.

Regarding the fuslogvw.exe, you must enable it first before bindings are being traced

![image](https://cloud.githubusercontent.com/assets/1467346/6869973/6b0d2856-d499-11e4-8ea1-08770d638c18.png)

It's possible you might have to reboot VS2013 if it remains empty, but you should be able to see something...

Either way, can you describe a good reproducible case, as in:

- create new empty web project
- add the following packages....
- add service reference pointing to a wsdl (can you try for instance with this free online webservice: http://www.service-repository.com/service/overview/517838238 so if you have issues with that one as well, then we can take your services out of the equation)
- add glimpse.mvc4
- BROKEN?....

**Comment by KevinBurton** [comment]
Still broken. I just started a new MVC project, added Elmah, Glimpse.Core, and Glimpse.ASP.NET. I ran the project and it showed the default ASP.NET page. Then I added Glimpse.MVC4 again I tried the application and it seemed to work. When I tried to add a service reference (with fuslogvw running as administrator and the settings set as you suggested) I get the error that I have illustrated earlier. Nothing showed up in fuslogvw. If I click on "settings" and close it out it seems to have the same effect as refresh. The UI seems questionable. I don't see an attempt to load Glimpse 1.8.2. I do see a failure for almost all the other Glimpse and Elmah assemblies. This is what I see:
![glimpse4](https://cloud.githubusercontent.com/assets/2643566/6873879/33a33e40-d481-11e4-85ec-8f9bd1205afa.jpg)

**Comment by CGijbels** [comment]
@KevinBurton do you have the same issue with the example soap service I provided? Otherwise we need your wsdl to try to reproduce it...

are these all bind failures shown in the printscreen? Or just all binds? Either way, you should be able to delete them all and then run the add service reference, then at least the new entries should be related to running the custom tool, _if_ that is the issue

**Comment by KevinBurton** [comment]
The problem is that these "error" seem to occur in a batch. They occur at the same time or near the same time and they occur all when i try to add a service reference. These are the new entries.

**Comment by CGijbels** [comment]
Ah ok, makes sense

could you send us the details for instance of the log entry for the Glimpse.Core 1.8.6 ? Just doubleclick it to get the details, you should be able to see the working directory there as well.

It is strange though that we see a fail entry for Glimpse.Core 1.8.6 and not for the 1.8.2
Regarding the 1.8.2, I think it is the Glimpse.Elmah assemlby that is linked to that one, so do you see a Glimpse.Elmah log entry in there somewhere?

Either way, do you have the same issue with the other service I pointed you to? It is just that I can still not reproduce the issue, which makes it kinda hard to figure it all out :wink:

**Comment by KevinBurton** [comment]
Forgive me but I am not sure how to check the log entry for Glimpse.Core 1.8.6. I am not sure where to double click on to get the log.

I don't try to install the Glimpse.Elmah package so I don't think it is the culprit. It is only when I try to install the Glimpse.MVC4 package that I start seeing the errors.

I don't seem to have access to http://www.service-repository.com/service/overview/517838238 as when I try to add a service reference to this service I get an error:
![glimpse5](https://cloud.githubusercontent.com/assets/2643566/6926483/3b56ffcc-d7ac-11e4-80be-e218c45cc1f2.jpg)

**Comment by CGijbels** [comment]
@KevinBurton the service url can be found at the link I mentioned, the link itself is not the service. If you go to that page then you'll find the following link: http://www.predic8.com:8080/shop/ShopService?wsdl which you should try to use...

I know you don't try to install the Glimpse.Elmah package, but is it already installed?
If so, do you have the same problem if you first uninstall that package and then add the Glimpse.Mvc4 package?

In the fuslogvw overview, you can just double-click on a specific entry or click on a log entry en choose `View Log` in the right menubar

Either way, the Glimpse.Elmah check (if applicable) might already give a better idea on the situation

**Comment by KevinBurton** [comment]
Thank you. I do not install and it is not already installed (Glimpse.Elmah).
I tried adding the service that you indicated rather than the one that I was trying and I no longer get the error about Glimpse 1.8.2 after I add Glimpse.MVC4. So what do you think this means? After installing Glimpse.MVC4 I can install and update the service that you specified but the service that I need to install will not install or update after Glimpse.MVC4 is installed. The error I get is detailed earlier as there is some reference to Glimpse 1.8.2. I cannot imagine that the service I install has a reference to Glimpse 1.8.2 as it is a service reference. It shouldn't matter but it does. One works and another doesn't. Ideas?

**Comment by avanderhoorn** [comment]
Is this still an issue for you?

**Comment by KevinBurton** [comment]
I have not been able to solve it yet.

**Comment by RakotVT** [comment]
I have same issue, when I try to create/update WCF service client. 
Installed Glimpse packages:
  <package id="Glimpse" version="1.8.6" targetFramework="net45" />
  <package id="Glimpse.AspNet" version="1.9.2" targetFramework="net45" />
  <package id="Glimpse.Mvc5" version="1.5.3" targetFramework="net45" />

![2015-12-25 22-07-19 foodmvc - microsoft visual studio administrator](https://cloud.githubusercontent.com/assets/11716360/12004157/ea48b3b0-ab53-11e5-8c59-fb7b93e05cbe.png)
